---
- name: Configuration Management Example
  hosts: all
  become: yes
  vars:
    app_config:
      server_name: "{{ inventory_hostname }}"
      max_connections: 100
      timeout: 300
      debug_mode: false

  tasks:
    - name: Create config directory
      file:
        path: /etc/myapp
        state: directory
        mode: '0755'

    - name: Generate base config file
      template:
        src: templates/myapp.conf.j2
        dest: /etc/myapp/myapp.conf
        mode: '0644'

    - name: Update specific configuration value
      lineinfile:
        path: /etc/myapp/myapp.conf
        regexp: '^debug_mode='
        line: 'debug_mode=true'