---
- name: Test connectivity
  hosts: all
  tasks:
    - name: Ping test
      ansible.builtin.ping:

    - name: Get hostname
      ansible.builtin.command: hostname
      register: hostname

    - name: Display hostname
      ansible.builtin.debug:
        var: hostname.stdout