---
- name: Ansible Vault Example - Secure Configuration Management
  hosts: all
  become: yes

  tasks:
    - name: Create application configuration directory
      file:
        path: /etc/myapp
        state: directory
        mode: '0755'

    - name: Create secure configuration file using vault variables
      template:
        src: templates/secure_app.conf.j2
        dest: /etc/myapp/secure.conf
        mode: '0600'
      notify: show_config_summary

    - name: Display partial secret values (safe for output)
      debug:
        msg: |
          API Key (first 8 chars): {{ secret_api_key[:8] }}...
          DB Password (first 4 chars): {{ db_password[:4] }}...
          App Secret (first 6 chars): {{ app_secret[:6] }}...

    - name: Show actual configuration file content (for verification)
      shell: cat /etc/myapp/secure.conf
      register: config_content
      changed_when: false

    - name: Display configuration content
      debug:
        var: config_content.stdout

    - name: Verify configuration was created
      stat:
        path: /etc/myapp/secure.conf
      register: config_file

    - name: Show configuration file info
      debug:
        msg: "Secure configuration file created at {{ config_file.stat.path }} with permissions {{ config_file.stat.mode }}"

  handlers:
    - name: show_config_summary
      debug:
        msg: "Secure configuration has been updated with vault-protected values"